# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on:  ubuntu-20.04
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_SECRET_KEY }}
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Get pip cache dir
      run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.PIP_CACHE_DIR }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/serve_requirements.txt') }}-v2
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Prepare to install dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade
    - name: Install / Cache APT Packages
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: redis-server firefox-geckodriver firefox
    - name: Install Pip dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f serve_requirements.txt ]; then pip install -r serve_requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: SSH into EC2 and deploy
      run: |
        eval $(ssh-agent -s)
        ssh-add <(echo "${{ secrets.CGPT_SERVER_KEY }}")
        ssh -A -o StrictHostKeyChecking=no LogLevel=ERROR ec2-user@${{ secrets.BASTION_HOST_IP }} "ssh backend 'cd /home/ubuntu/converseGPT && git pull -f && sudo systemctl restart cgpt'" 1>/dev/null
    - name: Test with pytest
      continue-on-error: true
      run: |
        cd tst
        pytest

        if [$? -ne 0]; then
          exit 1
        fi
    - name: Tag Commit successful if tests pass
      if: ${{ success() }}
      run: |
        git config --global user.email "32338288+hemenge133@users.noreply.github.com"
        git config --global user.name "Hayden Menge"
        git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic ${{ secrets.WORKFLOW_PAT }}"
        eval $(ssh-agent -s)
        ssh-add <(echo "${{ secrets.CGPT_SERVER_KEY }}")
        git tag -f last-successful-deployment $${{ github.sha }} && git push --tags -f
    - name: Rollback if tests fail
      if: ${{ failure() }}
      run: |
        eval $(ssh-agent -s)
        ssh-add <(echo "${{ secrets.CGPT_SERVER_KEY }}")
        ssh -A -o  StrictHostKeyChecking=no LogLevel=ERROR ec2-user@${{ secrets.BASTION_HOST_IP }} "ssh backend 'cd /home/ubuntu/converseGPT && git reset --hard last-successful-deployment && sudo systemctl restart cgpt'"
